import type { BoardTileSnapshot } from './gameStore';

export const demo_map: BoardTileSnapshot[] = [
  { x: 0, y: 0, state: 'typhon' },
  { x: 0, y: 1, state: 'water' },
  { x: 0, y: 2, state: 'island' },
  { x: 0, y: 3, state: 'monster', monsterType: 'monster_pieuvre' },
  { x: 0, y: 4, state: 'typhon' },
  { x: 0, y: 5, state: 'island' },
  { x: 0, y: 6, state: 'monster', monsterType: 'monster_serpent' },
  { x: 1, y: 0, state: 'monster', monsterType: 'monster_pieuvre' },
  { x: 1, y: 1, state: 'water' },
  { x: 1, y: 2, state: 'typhon' },
  { x: 1, y: 3, state: 'island' },
  { x: 1, y: 4, state: 'water' },
  { x: 1, y: 5, state: 'monster', monsterType: 'monster_baleine' },
  { x: 1, y: 6, state: 'island' },
  { x: 2, y: 0, state: 'island' },
  { x: 2, y: 1, state: 'typhon' },
  { x: 2, y: 2, state: 'monster', monsterType: 'monster_baleine' },
  { x: 2, y: 3, state: 'water' },
  { x: 2, y: 4, state: 'typhon' },
  { x: 2, y: 5, state: 'monster', monsterType: 'monster_pieuvre' },
  { x: 2, y: 6, state: 'water' },
  { x: 3, y: 0, state: 'monster', monsterType: 'monster_serpent' },
  { x: 3, y: 1, state: 'water' },
  { x: 3, y: 2, state: 'island' },
  { x: 3, y: 3, state: 'monster', monsterType: 'monster_pieuvre' },
  { x: 3, y: 4, state: 'water' },
  { x: 3, y: 5, state: 'typhon' },
  { x: 3, y: 6, state: 'island' },
  { x: 4, y: 0, state: 'typhon' },
  { x: 4, y: 1, state: 'island' },
  { x: 4, y: 2, state: 'typhon' },
  { x: 4, y: 3, state: 'water' },
  { x: 4, y: 4, state: 'island' },
  { x: 4, y: 5, state: 'monster', monsterType: 'monster_serpent' },
  { x: 4, y: 6, state: 'water' },
];
